import mongoose from 'mongoose';
import Car from '../models/Car';
import { config } from '../config/env';

const cars = [
    {
        name: 'Toyota Innova Crysta',
        manufacturer: 'Toyota',
        year: 2024,
        category: 'MUV',
        registrationNo: 'KA-01-MG-1001',
        seats: 7,
        transmission: 'Automatic',
        fuelType: 'Diesel',
        pricePerDay: 4500,
        pricePerHour: 400,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://static.toyotabharat.com/images/showroom/innova-mmc/gallery04-646x405.jpg',
        mileage: '12-15 kmpl',
        features: ['GPS Navigation', 'Music System', 'Safety Airbags', 'Leather Seats'],
    },
    {
        name: 'Honda City',
        manufacturer: 'Honda',
        year: 2024,
        category: 'Sedan',
        registrationNo: 'KA-01-MG-1002',
        seats: 5,
        transmission: 'Manual',
        fuelType: 'Petrol',
        pricePerDay: 2500,
        pricePerHour: 250,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://images.unsplash.com/photo-1678002239411-d633292ecbc4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aG9uZGElMjBjaXR5fGVufDB8fDB8fHww',
        mileage: '16-18 kmpl',
        features: ['GPS Navigation', 'Music System', 'Power Windows'],
    },
    {
        name: 'Maruti Swift Dzire',
        manufacturer: 'Maruti',
        year: 2023,
        category: 'Sedan',
        registrationNo: 'KA-01-MG-1003',
        seats: 5,
        transmission: 'Manual',
        fuelType: 'Petrol',
        pricePerDay: 2000,
        pricePerHour: 200,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://images.unsplash.com/photo-1663852408695-f57f4d75a536?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3V6dWtpJTIwc3dpZnR8ZW58MHx8MHx8fDA%3D',
        mileage: '22 kmpl',
        features: ['Music System', 'Power Windows', 'Central Locking'],
    },
    {
        name: 'Mahindra Scorpio',
        manufacturer: 'Mahindra',
        year: 2024,
        category: 'SUV',
        registrationNo: 'KA-01-MG-1004',
        seats: 7,
        transmission: 'Manual',
        fuelType: 'Diesel',
        pricePerDay: 3200,
        pricePerHour: 300,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://img.autocarindia.com/mmv_images/colors/20250714125907_Mahindra_Scorpio_Classic_Galaxy_Grey[1].jpg?w=728&q=75',
        mileage: '14 kmpl',
        features: ['GPS Navigation', '4WD', 'Music System', 'Power Steering'],
    },
    {
        name: 'Toyota Fortuner',
        manufacturer: 'Toyota',
        year: 2024,
        category: 'SUV',
        registrationNo: 'KA-01-MG-1005',
        seats: 7,
        transmission: 'Automatic',
        fuelType: 'Diesel',
        pricePerDay: 5500,
        pricePerHour: 500,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://img.autocarindia.com/mmv_images/colors/20250714023808_Toyota_Fortuner_Silver_Metallic[1].jpg?w=728&q=75',
        mileage: '10-12 kmpl',
        features: ['GPS Navigation', '4WD', 'Leather Seats', 'Sunroof', 'Premium Audio'],
    },
    {
        name: 'Mercedes E-Class',
        manufacturer: 'Mercedes',
        year: 2024,
        category: 'Luxury',
        registrationNo: 'KA-01-MG-1006',
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Petrol',
        pricePerDay: 8000,
        pricePerHour: 800,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://www.mbusa.com/content/dam/mb-nafta/us/myco/my26/e-class/e-sedan/class-page/2026-E-SEDAN-HC-D.jpg',
        mileage: '10-12 kmpl',
        features: ['Premium Audio', 'Leather Seats', 'Sunroof', 'GPS', 'Climate Control'],
    },
    {
        name: 'Maruti Ertiga',
        manufacturer: 'Maruti',
        year: 2024,
        category: 'MUV',
        registrationNo: 'KA-01-MG-1007',
        seats: 7,
        transmission: 'Manual',
        fuelType: 'Petrol',
        pricePerDay: 2800,
        pricePerHour: 280,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://cdni.autocarindia.com/ExtraImages/20241227062847_Maruti_Ertiga_showroom.jpg',
        mileage: '18-20 kmpl',
        features: ['Music System', 'Power Windows', 'Central Locking'],
    },
    {
        name: 'Hyundai i20',
        manufacturer: 'Hyundai',
        year: 2024,
        category: 'Economy',
        registrationNo: 'KA-01-MG-1008',
        seats: 5,
        transmission: 'Manual',
        fuelType: 'Petrol',
        pricePerDay: 2000,
        pricePerHour: 200,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://cdni.autocarindia.com/ExtraImages/20241115011846_2.png?w=728&q=75',
        mileage: '20-22 kmpl',
        features: ['Music System', 'Power Windows'],
    },
    {
        name: 'BMW 5 Series',
        manufacturer: 'BMW',
        year: 2024,
        category: 'Luxury',
        registrationNo: 'KA-01-MG-1009',
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Petrol',
        pricePerDay: 9500,
        pricePerHour: 950,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://media.zigcdn.com/media/model/2025/Nov/model-extimg-718324603_930x620.jpg',
        mileage: '12 kmpl',
        features: ['Premium Audio', 'Leather Seats', 'Panoramic Sunroof', 'GPS', 'Massage Seats'],
    },
    {
        name: 'Hyundai Creta',
        manufacturer: 'Hyundai',
        year: 2024,
        category: 'SUV',
        registrationNo: 'KA-01-MG-1010',
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Diesel',
        pricePerDay: 2800,
        pricePerHour: 280,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://imgd.aeplcdn.com/664x374/n/cw/ec/168697/creta-n-line-exterior-right-front-three-quarter-25.jpeg?isig=0&q=80',
        mileage: '17-18 kmpl',
        features: ['GPS Navigation', 'Sunroof', 'Ventilated Seats', 'Premium Audio'],
    },
    {
        name: 'Maruti Alto',
        manufacturer: 'Maruti',
        year: 2024,
        category: 'Economy',
        registrationNo: 'KA-01-MG-1011',
        seats: 5,
        transmission: 'Manual',
        fuelType: 'Petrol',
        pricePerDay: 800,
        pricePerHour: 80,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://navnitgroup.in/web/assets/images/car-list/Maruti-alto/alto4.jpg',
        mileage: '24-25 kmpl',
        features: ['Music System', 'Power Steering'],
    },
    {
        name: 'Audi A6',
        manufacturer: 'Audi',
        year: 2024,
        category: 'Luxury',
        registrationNo: 'KA-01-MG-1012',
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Petrol',
        pricePerDay: 10000,
        pricePerHour: 1000,
        status: 'Available',
        location: 'Bangalore',
        image: 'https://blogs.gomechanic.com/wp-content/uploads/2019/10/2019-audi-a6.jpg',
        mileage: '14 kmpl',
        features: ['Virtual Cockpit', 'Matrix LED', 'Premium Audio', 'Leather Interior'],
    }
];

const seedAllDB = async () => {
    try {
        await mongoose.connect(config.mongoUri);
        console.log('✅ Connected to MongoDB for full seeding');

        await Car.deleteMany({});
        console.log('🗑️ Cleared existing cars');

        await Car.insertMany(cars);
        console.log('🚗 Seeded all 12 cars successfully');

        process.exit();
    } catch (error) {
        console.error('❌ Error seeding database:', error);
        process.exit(1);
    }
};

seedAllDB();
